# Generated by Django 4.2 on 2026-03-23

import base64
import hashlib
import json
import logging
import os

from django.db import migrations

logger = logging.getLogger(__name__)


def encrypt_existing_secrets(apps, schema_editor):
    """
    Data migration: encrypt all existing plaintext secret values in PluginConfig.
    Secrets are identified via the Parameter.is_secret flag.
    """
    try:
        from cryptography.fernet import Fernet
    except ImportError:
        logger.warning(
            "cryptography library is not installed. Skipping secret encryption migration. "
            "Please install it and re-run migrations."
        )
        return

    # Derive the Fernet key the same way security.py does
    secret_raw = os.environ.get("PLUGIN_CONFIG_SECRET_KEY") or os.environ.get(
        "DJANGO_SECRET", "fallback-insecure-key"
    )
    fernet_key = base64.urlsafe_b64encode(hashlib.sha256(secret_raw.encode()).digest())
    fernet = Fernet(fernet_key)

    PluginConfig = apps.get_model("api_app", "PluginConfig")
    Parameter = apps.get_model("api_app", "Parameter")

    # Get all secret parameters
    secret_parameter_ids = set(Parameter.objects.filter(is_secret=True).values_list("id", flat=True))

    # Get all PluginConfigs for secret parameters
    secret_configs = PluginConfig.objects.filter(
        parameter_id__in=secret_parameter_ids,
    ).exclude(value__isnull=True)

    encrypted_count = 0
    skipped_count = 0

    for config in secret_configs:
        if config.value is None:
            continue

        # Check if already a valid Fernet token (starts with "gAAAAA" typically)
        raw_value = config.value
        if isinstance(raw_value, str):
            try:
                # Try to decrypt; if it succeeds, it's already encrypted
                fernet.decrypt(raw_value.encode("utf-8"))
                skipped_count += 1
                continue  # Already encrypted, skip
            except Exception:
                pass  # Not encrypted, proceed to encrypt

        # Encrypt the plaintext value
        try:
            plaintext = json.dumps(raw_value).encode("utf-8")
            encrypted = fernet.encrypt(plaintext).decode("utf-8")
            config.value = encrypted
            config.save(update_fields=["value"])
            encrypted_count += 1
        except Exception as e:
            logger.error(f"Failed to encrypt PluginConfig id={config.pk}: {e}")

    logger.info(
        f"Secret encryption migration complete: "
        f"{encrypted_count} encrypted, {skipped_count} already encrypted."
    )


def decrypt_existing_secrets(apps, schema_editor):
    """
    Reverse migration: decrypt all encrypted secret values back to plaintext.
    This allows rolling back the migration if needed.
    """
    try:
        from cryptography.fernet import Fernet, InvalidToken
    except ImportError:
        return

    secret_raw = os.environ.get("PLUGIN_CONFIG_SECRET_KEY") or os.environ.get(
        "DJANGO_SECRET", "fallback-insecure-key"
    )
    fernet_key = base64.urlsafe_b64encode(hashlib.sha256(secret_raw.encode()).digest())
    fernet = Fernet(fernet_key)

    PluginConfig = apps.get_model("api_app", "PluginConfig")
    Parameter = apps.get_model("api_app", "Parameter")

    secret_parameter_ids = set(Parameter.objects.filter(is_secret=True).values_list("id", flat=True))

    secret_configs = PluginConfig.objects.filter(
        parameter_id__in=secret_parameter_ids,
    ).exclude(value__isnull=True)

    for config in secret_configs:
        if not isinstance(config.value, str):
            continue
        try:
            plaintext = fernet.decrypt(config.value.encode("utf-8"))
            config.value = json.loads(plaintext.decode("utf-8"))
            config.save(update_fields=["value"])
        except (InvalidToken, Exception):
            pass  # Already plaintext, nothing to do


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0072_update_check_system"),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_secrets,
            reverse_code=decrypt_existing_secrets,
        ),
    ]
